### ISSUE TITLE
Error: please complete this security check

### ISSUE THREAD

**Issue by charlie-axsy** [jeevatkm/digitalocean-api-java#111]
I get a HTML response when trying to use the client in a process running on my server. 

The response contains the text `In order to keep DigitalOcean bot-free, please complete this security check`

Any tips?

**Comment by jeevatkm** [comment]
@charlie-axsy It seems DigitalOcean is blocking requests from your user id. Please contact DO support team for the same.

**Comment by charlie-axsy** [comment]
The problem was that my IP was blacklisted by Cloudflare.
