### ISSUE TITLE
getSlug() method in Image class started to return null values.

### ISSUE THREAD

**Issue by Zacorich** [jeevatkm/digitalocean-api-java#38]
Not a big deal but I suppose that something like {"images": [ { "id" : 3123213, "slug" : null }]} didn't happen in json response not so long ago. This is just for everyone to note as in my case I had to debug the json response to understand why library stopped working for me.

**Comment by jeevatkm** [comment]
@Zacorich Even though you have closed this. May I know the issue?

**Comment by Zacorich** [comment]
@jeevatkm The issues was that any getSlug() method calls needs to be checked on null values from now on. I was interpreting the string returned by getSlug() method and it was a surprise for me to see the null value there. I don't know whether it is a good practice to put null values in json objects, but we don't decide here as this is what Digital Ocean provide to us on response. As for me removing "slug" property from json object in case if it is null would be a better solution, but again we cannot decide here.

**Comment by Zacorich** [comment]
Here is a part of json I am talking about  
  {
      "id": 13411943,
      "name": "system.devpri.com-1441363249",
      "distribution": "CentOS",
      "slug": null,
      "public": true,
      "regions": [
        "nyc2"
      ],
      "created_at": "2015-09-04T10:40:49Z",
      "min_disk_size": 20,
      "type": "snapshot"
    },
