### ISSUE TITLE
Missing dependency?

### ISSUE THREAD

**Issue by russjr08** [jeevatkm/digitalocean-api-java#39]
I was trying to use the latest version of the library in my Android app, and ran into

    java.lang.NoClassDefFoundError: Failed resolution of: Lorg/apache/http/impl/client/HttpClients

from Android, I think it's missing a dependency. I got around it by adding HttpComponents to my app's build.gradle file

        compile group: 'org.apache.httpcomponents' , name: 'httpclient-android' , version: '4.3.5.1'

**Comment by jeevatkm** [comment]
My bad, I actually left this intentionally from POM and forget to document it. Thanks for informing me.

Will update documentation in in detail.

**Comment by jeevatkm** [comment]
Readme updated!
