### ISSUE TITLE
updateDomainRecord() updates only domain records name

### ISSUE THREAD

**Issue by soltiger** [jeevatkm/digitalocean-api-java#42]
updateDomainRecord() takes only records id and name as a parameter and there doesn't seem to be a way to update for example the record data.

**Comment by jeevatkm** [comment]
Adding option of complete domain record as an input. however "Any attribute valid for the record type can be set to a new value for the record." [More Info](https://developers.digitalocean.com/documentation/v2/#update-a-domain-record)

**Comment by jeevatkm** [comment]
Implemented and 2.3-SNAPSHOT pushed to maven repo with this changes. I will make an v2.3 release next week.
