### ISSUE TITLE
Infinite loop while getAvailableDroplets

### ISSUE THREAD

**Issue by yateya** [jeevatkm/digitalocean-api-java#50]
This happened to me while using https://github.com/jenkinsci/digitalocean-plugin . Jenkins plugin calls the function _getAvailableDroplets_, which keeps sending the request to _/droplets_, until it exhaust the 5000 query per hour.
Here is a similar bug report https://issues.jenkins-ci.org/browse/JENKINS-35022

**Comment by jeevatkm** [comment]
@yateya thanks for reporting. I'm glad to help out. 

[digitalocean-api-java](https://github.com/jeevatkm/digitalocean-api-java) will not call multiple times. Please have a look at this [method](https://github.com/jeevatkm/digitalocean-api-java/blob/master/src/main/java/com/myjeeva/digitalocean/impl/DigitalOceanClient.java#L236) method, it takes `pageNo` and `perPage` then performs one call to DigitalOcean and returns a response.

Can you please check with [them](https://github.com/jenkinsci/digitalocean-plugin), it looks like this [method](https://github.com/jenkinsci/digitalocean-plugin/blob/master/src/main/java/com/dubture/jenkins/digitalocean/DigitalOcean.java#L253) needs some love?

**Comment by yateya** [comment]
@jeevatkm Sorry for the report, it should be reported to jenkinsci/digitalocean-plugin. Thanks for you nice work :)

**Comment by jeevatkm** [comment]
@yateya you're welcome. Thanks.
