### ISSUE TITLE
How Can I access database using APIv2

### ISSUE THREAD

**Issue by younas-bangash** [jeevatkm/digitalocean-api-java#51]
Is it possible that we can access the database using apiv2 and insert and retrieve data using it ?

**Comment by jeevatkm** [comment]
@younas-bangash I'm sorry I couldn't understand your question. Which database?

**Comment by younas-bangash** [comment]
I have a droplet in my digital ocean server which have a database (mysql) how can i access that database through that api ?

**Comment by jeevatkm** [comment]
This library is used for interacting with [digitalocean API v2](https://developers.digitalocean.com/documentation/v2/) not the softwares installed by user on the droplet.
