### ISSUE TITLE
NullPointerException when deleting droplet in version 2.5

### ISSUE THREAD

**Issue by robertvazan** [jeevatkm/digitalocean-api-java#52]
java.lang.NullPointerException
	at com.myjeeva.digitalocean.impl.DigitalOceanClient.perform(DigitalOceanClient.java:1088)
	at com.myjeeva.digitalocean.impl.DigitalOceanClient.deleteDroplet(DigitalOceanClient.java:326)

This doesn't happen in version 2.4, so the bug is in changesets between 2.4 and 2.5. I dropped there with debugger and it looks like 2.5 assumes different REST response than the one actually received.

**Comment by jeevatkm** [comment]
Thanks for reporting, can you please provide some insight on response format?

**Comment by jeevatkm** [comment]
@robertvazan Can you please provide sample of response format?

**Comment by jeevatkm** [comment]
@robertvazan I found it. Applying fix.

**Comment by jeevatkm** [comment]
@robertvazan I have published [2.6-SNAPSHOT](https://oss.sonatype.org/content/repositories/snapshots/com/myjeeva/digitalocean/digitalocean-api-client/2.6-SNAPSHOT/) to OSS.

Can you please verify and share your feedback?
