### ISSUE TITLE
Add support for block storage (/v2/volumes)

### ISSUE THREAD

**Issue by Nackloose** [jeevatkm/digitalocean-api-java#54]
Are you planning on implementing the newly released [block storage](https://developers.digitalocean.com/documentation/v2/#block-storage)?

**Comment by jeevatkm** [comment]
Yep! I thought create it later. Thanks for creating it.

**Comment by jeevatkm** [comment]
@strokine has submitted PR for this feature. Once test cases and minor refactoring is done. PR #55 will be merged.

**Comment by jeevatkm** [comment]
- [ ] Take care of these [comments](https://github.com/jeevatkm/digitalocean-api-java/pull/55#issuecomment-237573768) and make a release.
