### ISSUE TITLE
Possibility to create volumes within creation of the droplet

### ISSUE THREAD

**Issue by srosato** [jeevatkm/digitalocean-api-java#56]
I see on the Digital Ocean API that it is possible to specify volumes to be attached at the creation of the droplet. Can that be added? I am trying to add to a Jenkins plugin that uses this wrapper and hit myself on this issue because we cannot fire two events simultaneously, we must wait for the droplet to be created before attaching the volume.

**Comment by jeevatkm** [comment]
I just checked the DO doc. It seems [create new droplet](https://developers.digitalocean.com/documentation/v2/#create-a-new-droplet) has `volume` input.

Sure, I will add it.

**Comment by srosato** [comment]
Wow thanks for the quick answer, looking forward to it! :)

**Comment by jeevatkm** [comment]
adding `tags` attribute also in the create droplet.

**Comment by jeevatkm** [comment]
Done, v2.8 SNAPSHOT published to OSS.

**Comment by srosato** [comment]
Thanks a lot! I have had a chance to test it and it works good :)

**Comment by jeevatkm** [comment]
Thanks, do not forget to give a star on github :)
