### ISSUE TITLE
Consider deleting resource by tag

### ISSUE THREAD

**Issue by lgueye** [jeevatkm/digitalocean-api-java#61]
Hi @jeevatkm ,

Thanks a lot for this digital ocean API client.
The REST API provides the ability to delete by tag. Unfortunately the client does not provide that feature.
Would you consider supporting it ?

Thank you for your work

**Comment by jeevatkm** [comment]
@lgueye Typically [DO change log](https://developers.digitalocean.com/documentation/changelog/) doesn't cover these improvements, I don't know why.

Thanks for reporting it.

I believe you're mentioning about [this API](https://developers.digitalocean.com/documentation/v2/#deleting-droplets-by-tag), sure I will add it.

**Comment by lgueye** [comment]
Hi @jeevatkm,

That's the one I'm talking about and many thanks for you support. 
Your library is invaluable to create a dev/prod/staging line within seconds instead of struggling with multiple curls.

**Comment by jeevatkm** [comment]
@lgueye `v2.9` is pushed to maven central with this API support.

**Comment by lgueye** [comment]
@jeevatkm thank you, I'll try to integrate it ASAP

**Comment by lgueye** [comment]
@jeevatkm I integrated it and works like a charm. 
Was able to delete my old ugly code.
Thank you!

**Comment by jeevatkm** [comment]
I'm glad to hear that. Thank you.
