### ISSUE TITLE
Tag rename will be deprecated April 26

### ISSUE THREAD

**Issue by mchitten** [jeevatkm/digitalocean-api-java#62]
Per [the DO developer docs](https://developers.digitalocean.com/documentation/changelog/api-v2/deprecating-update-tag/), tag rename (`PUT /v2/tags/:name`) will be deprecated on April 26. Please plan accordingly.

**Comment by jeevatkm** [comment]
@mchitten Thanks for the heads up. I will the remove [updateTag](https://github.com/jeevatkm/digitalocean-api-java/blob/master/src/main/java/com/myjeeva/digitalocean/DigitalOcean.java#L1257) API around April 26 and make a release.
