### ISSUE TITLE
Can't use Lib with Android Studio

### ISSUE THREAD

**Issue by idragon81** [jeevatkm/digitalocean-api-java#67]
Android has dropped support for http-client library

See [Stackoverflow](https://stackoverflow.com/questions/32153318/httpclient-wont-import-in-android-studio)

A mechanism to allow using our own client should solve this and other issues that could arise in the future

**Comment by jeevatkm** [comment]
I will have a look and get back. Thank you.

**Comment by jeevatkm** [comment]
I'm closing it, when I get a chance, I will update the HTTP client library to another (may be okhttp??)
