### ISSUE TITLE
Support for Firewall Configurations

### ISSUE THREAD

**Issue by aseemrastogi** [jeevatkm/digitalocean-api-java#72]
Hi - I could not find Java API for https://api.digitalocean.com/v2/firewalls
Is it supported?

Thanks

**Comment by jeevatkm** [comment]
@aseemrastogi Currently `/v2/firewalls` endpoints are not yet implemented.

**Comment by andreybleme** [comment]
Hi @jeevatkm. May I create an issue to implement the `firewalls` endpoints? Any thoughts on accepting a PR with these?

**Comment by jeevatkm** [comment]
@andreybleme Sure, you could provide PR for firewalls.

**Comment by jeevatkm** [comment]
Closing in favor of #83
