### ISSUE TITLE
getSimpleHeaderValue NullPointerException

### ISSUE THREAD

**Issue by rio123** [jeevatkm/digitalocean-api-java#73]
Since around one week I am getting the following NPE. It occurs only sporadically. I have changed the way I used the lib and upgraded to 2.12 at the same time, so I am not sure if the issue would occur with previous versions as well. Also it probably might be an issue with DigitalOcean itself, but in that case maybe could be handled nicer in the lib. I have seen it on the following methods: getActionInfo(),  getAllDropletSnapshots(), getDropletInfo(). Here is  a stacktrace:

```
00:00:05 Caused by: java.lang.NullPointerException
00:00:05 	at com.myjeeva.digitalocean.impl.DigitalOceanClient.getSimpleHeaderValue(DigitalOceanClient.java:1749)
00:00:05 	at com.myjeeva.digitalocean.impl.DigitalOceanClient.getSimpleHeaderValue(DigitalOceanClient.java:1761)
00:00:05 	at com.myjeeva.digitalocean.impl.DigitalOceanClient.appendRateLimitValues(DigitalOceanClient.java:1718)
00:00:05 	at com.myjeeva.digitalocean.impl.DigitalOceanClient.executeHttpRequest(DigitalOceanClient.java:1584)
00:00:05 	at com.myjeeva.digitalocean.impl.DigitalOceanClient.doGet(DigitalOceanClient.java:1532)
00:00:05 	at com.myjeeva.digitalocean.impl.DigitalOceanClient.perform(DigitalOceanClient.java:1499)
00:00:05 	at com.myjeeva.digitalocean.impl.DigitalOceanClient.getAllDropletSnapshots(DigitalOceanClient.java:1265)
00:00:05 	at ....

```

**Comment by jeevatkm** [comment]
@rio123 It seems DO is not sending rate limit header sometimes. Your suggestion is good, its better handle it gracefully in library.

Will work on it. Thank you for reporting an issue.
