### ISSUE TITLE
Pagination Not Working Correctly with /sizes Endpoint

### ISSUE THREAD

**Issue by Mac-Genius** [jeevatkm/digitalocean-api-java#80]
## Description

The function `getAvailableSizes` in the `DigitalOceanClient` class ignores the pageNo parameter.

This happens because `pageNo` is passed to the wrong `ApiRequest` constructor on [line 785](https://github.com/jeevatkm/digitalocean-api-java/blob/29c3afc0d352b4d12bd3694f475b6370538a5894/src/main/java/com/myjeeva/digitalocean/impl/DigitalOceanClient.java#L785) of the `DigitalOceanClient` class.

This may be an issue with other endpoints that use pagination.

## Possible Fix

Instead of using this constructor:

```java
public ApiRequest(ApiAction apiAction, Object data) {
  ...
}
```

Use the constructor that uses `pageNo` and `perPage`:

```java
public ApiRequest(ApiAction apiAction, Integer pageNo, Integer perPage) {
  ...
}
```

Then pass in the default `perPage` value on [line 785](https://github.com/jeevatkm/digitalocean-api-java/blob/29c3afc0d352b4d12bd3694f475b6370538a5894/src/main/java/com/myjeeva/digitalocean/impl/DigitalOceanClient.java#L785) of DigitalOceanClient:

```java
return (Sizes) perform(new ApiRequest(ApiAction.AVAILABLE_SIZES, pageNo, DEFAULT_PAGE_SIZE)).getData();
```

**Comment by jeevatkm** [comment]
@Mac-Genius Thank you for reporting it with detailed information. Yeah, I see an issue. I will fix it tonight or tomorrow and make a release.

**Comment by Mac-Genius** [comment]
Thank you!

**Comment by jeevatkm** [comment]
@Mac-Genius I hope everything seems alright, I'm closing this one. Thank you.

**Comment by Mac-Genius** [comment]
@jeevatkm Sorry it took me so long, everything seems to be working properly now. Thank you!

**Comment by jeevatkm** [comment]
@Mac-Genius no worries, good to hear its working properly.
