### ISSUE TITLE
Image slug information missing in Image object part of Droplet we get from getDropletInfo API

### ISSUE THREAD

**Issue by tanmally** [jeevatkm/digitalocean-api-java#82]
com.myjeeva.digitalocean.pojo.Image@1d844adb[id=34175186,name=18.04 x64,distribution=Ubuntu,**slug=<null>**,availablePublic=false,regions=[nyc1, sfo1, nyc2, ams2, sgp1, lon1, nyc3, ams3, fra1, tor1, sfo2, blr1],createdDate=Wed May 09 08:10:21 IST 2018,minDiskSize=20,size=0.35,type=snapshot,rateLimit=<null>]

**Comment by tanmally** [comment]
It happens for few images ..not for all

**Comment by jeevatkm** [comment]
@tanmally Thanks for creating an issue. I have just verified the DO API doc. Attribute name `slug` is correct.

```
https://developers.digitalocean.com/documentation/v2/#images

slug | nullable string | A uniquely identifying string that is associated with each of the DigitalOcean-provided public images. These can be used to reference a public image as an alternative to the numeric id.
```

My best guess; it could be related with those particular image missing a value at DO end. I think its better to report it DO from your account support.

**Comment by tanmally** [comment]
Looks like an issue at DO side . I tired to query the image Id and got resource not found exception. I shall report it to DO API team

**Comment by jeevatkm** [comment]
Closing it.
