### ISSUE TITLE
Add support for managed /v2/databases

### ISSUE THREAD

**Issue by erichelgeson** [jeevatkm/digitalocean-api-java#96]
Docs https://developers.digitalocean.com/documentation/v2/#databases

**Comment by jeevatkm** [comment]
@erichelgeson Thanks for creating an issue.

**Comment by erichelgeson** [comment]
no problem - just FYI I've been playing around with the new databases api and ran into this - not sure if it'd cause an issue on your end or not https://github.com/digitalocean/api-v2/issues/175

**Comment by jeevatkm** [comment]
@erichelgeson Thanks for heads-up. Technically it would cause an issue. It seems DO have resolved it. By any chances, if you're working on this to create implementation, are you interested in providing PR?

**Comment by erichelgeson** [comment]
@jeevatkm no unfortunately - using a different api client for my needs.

**Comment by neuharthr** [comment]
Hi @erichelgeson. Did you intend to do a PR for this? It would be very useful for this library to have that.

**Comment by erichelgeson** [comment]
I do not intend to.
